version: '3'

services:
  web3:
    build: .
    command: ./books_init.sh
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'books'
    restart: always
    volumes:
      - .:/code
    expose:
       - 8084
    depends_on:
      - db

  nginx2:
    container_name: 'srv2'
    restart: always
    image: nginx:latest
    depends_on: 
      - web3
    ports:
      - 84:80
    volumes:
      - ./nginx:/etc/nginx/conf.d #папка для конфигурации nginx
      - ./static:/srv/www/static/ #статика приложения
      - ./logs:/srv/www/logs/ # удаляется папка в контейнере и заменяется на папку их хоста, логи nginx

  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: sergey
      POSTGRES_DB: bookbase
     
