# Generated by Django 3.2 on 2021-04-20 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('year_of_create', models.DateField(blank=True, default=datetime.date(1990, 1, 1))),
            ],
        ),
    ]
