# Generated by Django 3.2 on 2021-04-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
    ]
